FROM php:7.1-fpm

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
    && docker-php-ext-install -j$(nproc) iconv mcrypt \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd
    
RUN docker-php-ext-install pdo_mysql
    
VOLUME /app

WORKDIR /app

ADD ./idle.sh /idle.sh

RUN chmod +x /idle.sh

RUN echo test-frontend nginx >> /etc/hosts

CMD ["/bin/sh", "-c", "echo Migration_test wait 20 sec && sleep 20 && /app/yii_test_migrate migrate/up --interactive=0 && /app/vendor/bin/codecept build && /app/yii_test rbac/init && /idle.sh"]