version: "2"
services:
    nginx:
        build:
            context: ./docker
            dockerfile: Dockerfile-nginx
        ports: 
            - "80:80"
        volumes:
            - ./app:/app:rw
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: ./docker
            dockerfile: Dockerfile-php-fpm
        volumes:
            - ./app:/app:rw
        depends_on:
            - init-app
    init-app:
        build:
            context: ./docker
            dockerfile: Dockerfile-init-app
        volumes:
            - ./app:/app:rw
        depends_on:
            - composer
            - mysql
        restart: on-failure
    composer:
       build:
           context: ./docker
           dockerfile: Dockerfile-composer
       volumes:
           - ./app:/app:rw
    mysql:
        build:
            context: ./docker
            dockerfile: Dockerfile-mysql
        ports: 
            - "3307:3306"
        volumes:
            - ./docker/runtime/mysql:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: root
        