version: "2"
services:
    nginx:
        build:
            context: ./docker/dev
            dockerfile: Dockerfile-nginx
        ports: 
            - "80:80"
        volumes:
            - ./app:/app
            - ./docker/dev/nginx.conf.d:/etc/nginx/conf.d
        depends_on:
            - php-fpm
    nginx-test:
        build:
            context: ./docker/dev
            dockerfile: Dockerfile-nginx-test
        ports: 
            - "8080:80"
        volumes:
            - ./app:/app
            - ./docker/dev/nginx-test.conf.d:/etc/nginx/conf.d
        depends_on:
            - test-app
    php-fpm:
        build:
            context: ./docker/dev
            dockerfile: Dockerfile-php-fpm
        volumes:
            - ./app:/app
        depends_on:
            - test-app
    test-app:
        build:
            context: ./docker/dev
            dockerfile: Dockerfile-test-app
        volumes:
            - ./app:/app
        depends_on:
            - init-app
            - selenium
        restart: on-failure
    init-app:
        build:
            context: ./docker/dev
            dockerfile: Dockerfile-init-app
        volumes:
            - ./app:/app
        depends_on:
            - composer
            - mysql
        restart: on-failure
    composer:
       build:
           context: ./docker/dev
           dockerfile: Dockerfile-composer
       volumes:
           - ./app:/app
    mysql:
        build:
            context: ./docker/dev
            dockerfile: Dockerfile-mysql
        ports: 
            - "3307:3306"
        volumes:
            - ./docker/runtime/mysql:/var/lib/mysql
            - ./docker/dev/mysql.conf.d:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: root
    selenium:
        image: selenium/standalone-chrome
        