version: "2"
services:
    nginx:
        build:
            context: ./docker
            dockerfile: Dockerfile-nginx
        ports: 
            - "80:80"
        volumes:
            - ./app:/app
            - ./docker/nginx.conf.d:/etc/nginx/conf.d
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: ./docker
            dockerfile: Dockerfile-php-fpm
        volumes:
            - ./app:/app
        depends_on:
            - test-app
    test-app:
        build:
            context: ./docker
            dockerfile: Dockerfile-test-app
        volumes:
            - ./app:/app
        depends_on:
            - init-app
        restart: on-failure
    init-app:
        build:
            context: ./docker
            dockerfile: Dockerfile-init-app
        volumes:
            - ./app:/app
        depends_on:
            - composer
            - mysql
        restart: on-failure
    composer:
       build:
           context: ./docker
           dockerfile: Dockerfile-composer
       volumes:
           - ./app:/app
    mysql:
        build:
            context: ./docker
            dockerfile: Dockerfile-mysql
        ports: 
            - "3307:3306"
        volumes:
            - ./docker/runtime/mysql:/var/lib/mysql
            - ./docker/mysql.conf.d:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: root
        