# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM composer

VOLUME /app

WORKDIR /app

CMD ["composer", "install"]

