FROM nginx

RUN rm /etc/nginx/conf.d/default.conf

ADD ./nginx-frontend.conf /etc/nginx/conf.d/frontend.conf
ADD ./nginx-backend.conf /etc/nginx/conf.d/backend.conf

VOLUME /app

CMD ["nginx", "-g", "daemon off;"]
