# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM mysql:5.7

VOLUME /var/lib/mysql

CMD ["mysqld"]